# Project identification
sonar.projectKey=himanshigaba22_8.2CDevSecOps
sonar.organization=himanshigaba22

# SonarCloud host
sonar.host.url=https://sonarcloud.io

# Authentication (provided via Jenkins, not here)
# sonar.login is handled by SONAR_TOKEN in Jenkins

# Code language and sources
sonar.language=js
sonar.sources=.

# Optional: add tests folder if needed
sonar.tests=tests

# Encoding
sonar.sourceEncoding=UTF-8
